import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const core=fs.readFileSync(new URL('../assets/today-guide-core.js',import.meta.url),'utf8'),ui=fs.readFileSync(new URL('../assets/today-guide.js',import.meta.url),'utf8');
function harness(){
 const nodes=new Map();class Node{constructor(){this.events={};this.children=[];this.dataset={};this.hidden=false;this.attrs={};}set id(v){this._id=v;nodes.set(v,this);}get id(){return this._id;}setAttribute(k,v){this.attrs[k]=v;}addEventListener(k,fn){this.events[k]=fn;}append(...args){this.children.push(...args);}after(){}replaceChildren(){this.children=[];}querySelectorAll(){return [];}focus(){}showModal(){this.open=true;}close(){this.open=false;this.events.close?.();}click(){this.events.click?.({currentTarget:this});}}
 const q=id=>{if(!nodes.has(id)){const n=new Node();n.id=id;}return nodes.get(id);};
 const events={},window={addEventListener(k,fn){events[k]=fn;},setInterval(){}};
 class FixedDate extends Date{constructor(...args){super(...(args.length?args:['2026-10-07T00:00:00Z']));}}
 const context={window,Date:FixedDate,IS_TEST_MODE:true,items:[{id:'one',date:'2026-10-07',type:'task',title:'답장',endTimeUnknown:true},{id:'two',date:'2026-10-07',type:'task',title:'공부',recurrence:{frequency:'weekly'}},{id:'next',date:'2026-10-14',type:'task',title:'공부'}],persist(){context.saved++;if(context.fail)throw Error('quota');},renderView(){window.DAYFLOW_GUIDE.refresh();},openDayDetails(key){context.opened=key;},saved:0};
 const document={getElementById:q,createElement:()=>new Node(),body:new Node(),querySelector:()=>new Node(),addEventListener(){}};context.document=document;vm.createContext(context);vm.runInContext(core,context);vm.runInContext(ui,context);return {context,q,events};
}
test('start only marks session; complete persists one record and undo restores eligibility',()=>{const h=harness();h.q('guide-start').click();assert.equal(h.context.saved,0);assert.equal(h.q('guide-status').textContent,'진행 중');h.q('guide-complete').click();assert.equal(h.context.items[0].completed,true);assert.equal(h.context.saved,1);assert.equal(h.q('guide-task-title').textContent,'공부');h.q('guide-completed-list').children[0].children[1].click();assert.equal(h.context.items[0].completed,false);assert.equal(h.q('guide-task-title').textContent,'답장');});
test('defer requires explicit confirmation; cancel leaves original date; only one occurrence moves',()=>{const h=harness();h.q('guide-skip').click();h.q('guide-defer').click();assert.equal(h.context.saved,0);assert.equal(h.q('guide-defer-confirmation').hidden,false);h.q('guide-defer-cancel').click();assert.equal(h.context.items[1].date,'2026-10-07');h.q('guide-defer').click();h.q('guide-defer-confirm').click();assert.equal(h.context.items[1].date,'2026-10-08');assert.equal(h.context.items[2].date,'2026-10-14');assert.equal(h.context.items[1].recurrence.frequency,'weekly');assert.equal(h.context.saved,1);});
test('storage failure rolls back completion and date, gives actionable error',()=>{const h=harness();h.context.fail=true;h.q('guide-complete').click();assert.equal(h.context.items[0].completed,undefined);assert.match(h.q('guide-action-status').textContent,/저장하지 못/);h.q('guide-defer').click();h.q('guide-defer-confirm').click();assert.equal(h.context.items[0].date,'2026-10-07');});
test('stale confirmation cannot affect switched account; account change closes and resets view',()=>{const h=harness();h.q('guide-defer').click();h.context.items=[];h.events['dayflow-sharing-account-change']();h.q('guide-defer-confirm').click();assert.equal(h.context.saved,0);assert.equal(h.q('today-guide-dialog').open,false);assert.equal(h.q('guide-task-title').textContent,'오늘 등록된 할 일이 없습니다');});
test('opening recommendation never saves and add opens actual Seoul today',()=>{const h=harness();h.q('today-guide-menu').click();assert.equal(h.context.saved,0);assert.equal(h.q('today-guide-dialog').open,true);h.q('guide-add').click();assert.equal(h.context.opened,'2026-10-07');assert.equal(h.context.saved,0);});
